---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-service-config

data:
    config.yaml: |-
      host: '0.0.0.0'
      port: 80
      in_cluster: true
      debug: true
      # 10 - debug
      log_level: 10
      tenant_service_url: 'http://192.168.0.34:32280/services/v1/tenant/tenants'
      nfs_server: '192.168.0.31'
      nfs_prefix: '/opt/minio-root/'
      MOOPKEY: 'faf23ej21fklajfla'
