---
apiVersion: v1
kind: Service
metadata:
  name: tenant-service
spec:
  ports:
  - name: tenant-service-http
    nodePort: 31778
    port: 7778
    protocol: TCP
    targetPort: 80
  selector:
    app: moop
    service: tenant-service
  type: NodePort
