---
apiVersion: v1
kind: Service
metadata:
  name: volume-service
spec:
  ports:
  - name: volume-service-http
    nodePort: 31010
    port: 80
    protocol: TCP
    targetPort: 5010
  selector:
    app: moop
    service: volume-service
  type: NodePort
